from pathlib import Path

# GENERAL
ENABLE_COLLAPSE_ANIMATION = True
LABEL_DEFAULT_TEXT = "Captions Placeholder"
FONT_FAMILY = "Segoe UI"
SECONDARY_ACTION_INDICATOR_ACTIVE = False
EXCLUDE_OVERLAY_FROM_CAPTURE = False

# CAPTURE / PREVIEW
CAPTURE_FPS = 30
CAPTURE_FLIP_HORIZONTAL = True
SIGN_PREDICTION_MIN_CONFIDENCE = 0.15
DETECTION_MAX_DIM = 640
DETECTION_MIN_DIM = 320
ENABLE_DETECTION_RESIZE = True
ENABLE_DETECTION_SQUARE = True
SELECTION_INSTRUCTION_TEXT = "Drag to select capture region. Press ENTER or SPACE to confirm."
SELECTION_TEXT_FONT_SIZE = 13
SELECTION_TEXT_MARGIN_TOP = 20
SELECTION_DIM_ALPHA = 120
SELECTION_BORDER_WIDTH = 1
HIGHLIGHT_BORDER_WIDTH = 1
HIGHLIGHT_DURATION_MS = 1000
PREVIEW_WIDTH = 320
PREVIEW_HEIGHT = 180
PREVIEW_MARGIN = 24
PREVIEW_TITLE_HEIGHT = 28
PREVIEW_TITLE_BG = "rgba(18, 18, 20, 235)"
PREVIEW_TITLE_TEXT = "rgba(255, 255, 255, 235)"
PREVIEW_TITLE_SUBTEXT = "rgba(255, 255, 255, 200)"
PREVIEW_REGION_BG = "rgba(0, 0, 0, 160)"
PREVIEW_REGION_TEXT = "rgba(255, 255, 255, 220)"
PREVIEW_HINT_TEXT = "rgba(255, 255, 255, 200)"
STATUS_UPDATE_INTERVAL_MS = 500
STATUS_PANEL_PADDING = 10
STATUS_PANEL_BG = "rgba(20, 20, 22, 235)"
STATUS_PANEL_BORDER = "rgba(255, 255, 255, 24)"
STATUS_PANEL_TEXT = "rgba(255, 255, 255, 220)"
STATUS_PANEL_TITLE = "rgba(255, 255, 255, 235)"
STATUS_PANEL_FONT_SIZE = 12
STATUS_PANEL_TITLE_SIZE = 13

# OVERLAY WINDOW
OVERLAY_WIDTH = 520
OVERLAY_MARGIN = 20
OUTER_PADDING = 10
PANEL_SPACING = 8
SECONDARY_EXPANDED_HEIGHT = 420
ANIMATION_DURATION_MS = 220
RADIUS = 14

# PRIMARY PANEL
PRIMARY_INNER_SPACING = 10
BUTTON_COLUMN_SPACING = 8
BUTTON_WIDTH = 40
BUTTON_HEIGHT = 32
CAPTION_HORIZONTAL_PADDING = 12
CAPTION_VERTICAL_PADDING = 8
DEFAULT_FONT_SIZE = 14
PRIMARY_BOX_SIZE_MIN = 90
PRIMARY_BOX_SIZE_MAX = 260
DEFAULT_PRIMARY_BOX_SIZE = 110

# SECONDARY PANEL
SECONDARY_INNER_SPACING = 24
SECONDARY_COLUMN_SPACING = 20
SECONDARY_ACTION_ROW_SPACING = 10
SECONDARY_LABEL_FONT_SIZE = 16
SECONDARY_CONTROL_FONT_SIZE = 15
SECONDARY_CONTROL_MIN_HEIGHT = 36
SECONDARY_SLIDER_GROOVE_HEIGHT = 8
SECONDARY_SLIDER_HANDLE_SIZE = 20
SECONDARY_CHECKBOX_MIN_HEIGHT = 30
SECONDARY_DROPDOWN_WIDTH = 30
SECONDARY_ACTION_BUTTON_SIZE = 40
SECONDARY_ACTION_ICON_SIZE = 20

# OPACITY
DEFAULT_OPACITY = 0.80
MIN_OPACITY_PERCENT = 50
MAX_OPACITY_PERCENT = 100

# COLORS
TEXT_COLOR = "rgba(255, 255, 255, 235)"
PRIMARY_BG = "rgba(28, 28, 30, 255)"
SECONDARY_BG = "rgba(40, 40, 43, 255)"
BORDER_COLOR = "rgba(255, 255, 255, 28)"
BUTTON_BG = "rgba(255, 255, 255, 24)"
BUTTON_HOVER_BG = "rgba(255, 255, 255, 52)"

# OPTIONS
CORNER_TOP_LEFT = "Top Left"
CORNER_TOP_RIGHT = "Top Right"
CORNER_BOTTOM_LEFT = "Bottom Left"
CORNER_BOTTOM_RIGHT = "Bottom Right"
DEFAULT_CORNER = CORNER_BOTTOM_RIGHT
CORNER_OPTIONS = [CORNER_TOP_LEFT, CORNER_TOP_RIGHT, CORNER_BOTTOM_LEFT, CORNER_BOTTOM_RIGHT]
MODEL_OPTIONS = ["Local Small", "Local Medium"]

# PREFERENCES
PROJECT_DIR = Path(__file__).resolve().parent
DEFAULT_SETTINGS_PATH = PROJECT_DIR / "default_settings.json"
USER_PREFERENCES_PATH = PROJECT_DIR / "user_preferences.json"

DEFAULT_SETTINGS = {
    "caption_box_size": DEFAULT_PRIMARY_BOX_SIZE,
    "opacity_percent": int(DEFAULT_OPACITY * 100),
    "show_raw_tokens": False,
    "freeze_on_detection_loss": False,
    "enable_llm_smoothing": False,
    "model_selection": MODEL_OPTIONS[0],
    "show_latency": False,
    "corner": DEFAULT_CORNER,
}
